### PR TITLE
Creativenovels.com article

### PR DESCRIPTION
**Pull request by basilevs**
Navigation section fail!

The page has navigation section, that appears empty after parsing.
It should be possible to show it with rewrite, but rewrite is not applicable for body rule.

To work around that, either  next/previous links are required to be present in template or some kind of matches concatenation is required.

### CODE REVIEW

**Comment by dsavenko** [comment]
Looks like we should have prev/next navigation in `article` templates. Let me modify current templates to support it (if provided). I will merge this PR afterwards.

**Comment by dsavenko** [comment]
Added navigation to all templates. This is what you need to add to the parser:

```yaml
  - name: nav_prev_link
    match:
      include: "span.temp a.prevkey:first"
      attribute: href

  - name: nav_prev
    value: "<< Previous"

  - name: nav_next_link
    match: 
      include: "span.temp a.nextkey:first"
      attribute: href

  - name: nav_next
    value: "Next >>"
```

Could you please modify this according to your preferences and update the PR?

**Comment by basilevs** [comment]
Will do.

**Comment by basilevs** [comment]
Lets leave this until I have to visit the site again.

**Pull request closed without merging**
